trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Services/DemoAPI/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  rootDirectory: 'Services/DemoAPI'

steps:

- task: DotNetCoreCLI@2
  displayName: 'Function - Build project'
  inputs:
    projects: ' $(rootDirectory)/**/*.csproj'
    arguments: '--output publish_output --configuration Release'
- task: DotNetCoreCLI@2
  displayName: 'Publish project'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(rootDirectory)/**/*.csproj'
    arguments: '--configuration Release --output $(build.artifactstagingdirectory)'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'App'
    publishLocation: 'pipeline'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: ' $(rootDirectory)/Infrastructure'
    artifact: 'Infrastructure'
    publishLocation: 'pipeline'