trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Services/DemoAPI/*

variables:
  rootDirectory: 'Services/DemoAPI'
  azureSubscription: 'Demo Account'
  resourceGroupName: 'demo-az-app-configuration'
  region: 'eastus'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:

    - task: DotNetCoreCLI@2
      displayName: 'Function - Build project'
      inputs:
        projects: ' $(rootDirectory)/**/*.csproj'
        arguments: '--output publish_output --configuration Release'
    - task: DotNetCoreCLI@2
      displayName: 'Publish project'
      inputs:
        command: publish
        publishWebProjects: false
        projects: '$(rootDirectory)/**/*.csproj'
        arguments: '--configuration Release --output $(build.artifactstagingdirectory)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'App'
        publishLocation: 'pipeline'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: ' Infrastructure'
        artifact: 'Infrastructure'
        publishLocation: 'pipeline'

